// example/vue-example/src/App.vue
<template>
    <div>
        <div class="title">
            <h2 v-if="name !== ''">Hey, {{name}}.</h2>
            <Hello v-else :name="defaultName" />
        </div>

        <div>
            <p>Count: {{count}}</p>

            <button v-on:click="increment">+</button>
            
            <button v-on:click="reset">Reset</button>
        </div>
    </div>
</template>
 
<script>
    import Hello from './components/Hello.vue'
    import store from './vuex/store.js'
 
    export default {
        name: 'App',
        props: ['name'],
        data: () => { 
            return {
                defaultName: 'Jenni',
            }
        },
        components: {
            Hello
        },
        computed: {
            count() {
                return store.state.count
            }
        },
        mounted() { console.log('mount') },
        methods: {
            exampleMethode: function() { console.log('methode') },
            increment: function() {
                store.commit('increment');
            },
            reset: function() {
                store.commit('reset');
            }
        }
    }
</script>
      
<style>
    @import './greeting.css'
</style>

// example/react-example/src/js/App.js
import React from 'react'
import ClassGreeting from './components/class/ClassGreeting.js'
import FunctionalGreeting from './components/functional/FunctionalComponent.js'
import store from '../redux/store.js'
import { increment, reset } from '../redux/actions/counter.js'
import { connect } from "react-redux";

function App(props) {
    const name = 'Thomas Schulz';
    
    const element = <h1>Hello, {name} in JSX.</h1>;

    const incrementCount = () => {
        console.log("increment")
        store.dispatch(increment())
    }

    const resetCount = () => {
        console.log("reset")
        store.dispatch(reset())
        // store.dispatch(reset)
    }

    return (
        <div>
            <p>Class Component</p>
            <ClassGreeting name='Jack' />

            <p>Functional Component</p>
            <FunctionalGreeting name='' />

            <p>Redux</p>
            <p>Count: {props.count}</p>
            <button onClick={incrementCount}>+</button>
            <button onClick={resetCount}>Reset</button>

            <p>JSX</p>
            {element}
        </div>
    );
}

const mapStateToProps = state => {
    return {
        count: state.counter.count
    };
};

export default connect(mapStateToProps)(App);
