// project/vuejs3/src/components/Artist/ArtistList.vue
<template>
    <div class="flex-container-column">
        <div class="list-container">
            <div v-for="item in artists.docs" :key="item._id">
                <ArtistItem :item="item" :showButtons="showButtons"/>
            </div>
        </div>
        <div class="flex-container-row">
            <div class="flex-container-column margin20">
                <button v-if="artists.hasNextPage" class="button" v-on:click="this.handleMoreButton">Load More</button>
            </div>
        </div>
    </div>
</template>

<script>
    import ArtistItem from './ArtistItem.vue'

    export default {
        props: ['handleMoreButton', 'artists', 'showPaginate', 'showButtons'],
        components: {
            ArtistItem
        }
    }
</script>

// project/sveltejs/src/components/Artist/ArtistList.svelte
<script>
    import ArtistItem from './ArtistItem.svelte'

    export let artists
    export let showPaginate
    export let handleMoreButton
    export let showButtons

</script>

<div class="flex-container-column">
    <div class="list-container">
        {#each artists.docs as item}
            <ArtistItem item={item} showButtons={showButtons} />
        {/each}
    </div>
    <div>
        {#if showPaginate}
            <div class="flex-container-row">
                <div class="flex-container-column margin20">
                    {#if artists.hasNextPage}
                        <button class="button" on:click={() => handleMoreButton()}>Load More</button>
                    {/if}
                </div>
            </div>
        {/if}
    </div>
</div>
