// project/reactjs/src/js/pages/Group/GroupUpdate.js
import React, { useState, useEffect } from 'react'  
import { useParams } from 'react-router-dom' 
import Axios from 'axios'  
import GroupForm from '../../components/Group/GroupForm'
import Error422 from '../Error/Error422'

function GroupUpdate() {
    const [isLoading, setIsLoading] = useState(true)
    const {id} = useParams()  
    const [data, setData] = useState({})
    const [isError, setIsError] = useState(null)

    useEffect (() => {
        Axios
        .get(`http://localhost:8000/groups/${id}`)
        .then((res) => {
            setData(res.data)
            setIsLoading(false)
        })
        .catch((err) => {
            setIsError(err.response.status)
            setIsLoading(false)
        })

        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [])

    return(
        <div>
            { (isLoading === false && isError === null) &&
                <div>
                    <h2 className="title">Update Group</h2>

                    <GroupForm data={data} actionType="update" id={id}/>
                </div>
            }

            { (isLoading === false && isError === 433) &&
                <Error422/>
            }
        </div>
    )
}  
  
export default GroupUpdate

// project/vuejs3/src/pages/Group/GroupUpdate.vue
<template>
    <div>
        <div v-if="isLoading === false && isError === null">
            <h2 class="title">Update Group</h2>

            <GroupForm :data="data" :actionType="actionType" :id="id"/>
        </div>

            <Error422 v-if="isLoading === false && isError === 433"/>
    </div>
</template>

<script>
    import Axios from 'axios'
    import GroupForm from '../../components/Group/GroupForm.vue'
    import Error422 from '../Error/Error422.vue'

    export default {
        name: 'GroupUpdate',
        components: {
            GroupForm,
            Error422
        },
        props: ['id'],
        data: function() {
            return {
                data: {},
                isLoading: true,
                isError: null,
                actionType: 'update'
            }
        },
        mounted() {
            Axios
            .get(`http://localhost:8000/groups/${this.id}`)
            .then((res) => {
                this.data = res.data
                this.isLoading = false
            })
            .catch((err) => {
                this.isError = err.response.status
                this.isLoading = false
            })
        }
    }
</script>
