// project/reactjs/src/js/pages/Group/Group.js
import React, { useState, useEffect } from 'react'  
import Axios from 'axios'  
import { useParams } from 'react-router-dom' 
import ArtistList from '../../components/Artist/ArtistList.js'
import ReactQuill from 'react-quill'  
import 'react-quill/dist/quill.snow.css'  
import Error404 from '../Error/Eroro404'

function Group() {
    const [group, setGroup] = useState('')
    const [isLoading, setIsLoading] = useState(true)
    const {id} = useParams()  
    const [isError, setIsError] = useState(null)

    useEffect (() => {
        Axios
        .get(`http://localhost:8000/groups/${id}`)
        .then((res) => {
            setGroup(res.data)
            setIsLoading(false)
        })
        .catch((err) => {
            setIsError(err.response.status)
            setIsLoading(false)
        })

        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [])  

    return (
        <div>
            { (isLoading === false && isError === null) && 
                <div className="flex-container-column">
                     
                    <img className="img" src={group.groupImageLink} alt="bild" />  
                    
                    <h1 className="title list-item-title">{group.name}</h1>  

                    <div className="list-item-personal-description">
                        { group.debutDate !== "" &&
                            <div className="list-item-personal-description-container">
                                <h3 className="list-item-personal-description-title">Debut Date</h3>
                                <p className="list-item-personal-description-text">{group.debutDate}</p>
                            </div>
                        }

                        { group.companies !== "" &&
                            <div className="list-item-personal-description-container">
                                <h3 className="list-item-personal-description-title">Companies</h3>
                                <p className="list-item-personal-description-text">{group.companies}</p>
                            </div>
                        }

                        { group.fandomName !== "" &&
                            <div className="list-item-personal-description-container">
                                <h3 className="list-item-personal-description-title">Fandom Name</h3>
                                <p className="list-item-personal-description-text">{group.fandomName}</p>
                            </div>
                        }
                    </div>

                    { (group.facts !== "" && group.facts !== "<p><br></p>") &&
                        <div className="list-item-personal-description-addictional-container">
                            <h3 className="list-item-personal-description-title">Facts</h3>
                            <ReactQuill 
                                readOnly={true}
                                theme={"bubble"}
                                id='editor'
                                value={group.facts} 
                                className="readQuill"
                            >
                            </ReactQuill>
                        </div>
                    }

                    { group.artists.docs.length !== 0 &&
                        <div className="list-item-personal-description-addictional-container">
                            <h3 className="list-item-personal-description-title">Active Artists</h3>
                            { group.artists !== undefined && <ArtistList artists={group.artists} showPaginate={false} /> }
                        </div>
                    }

                    { group.formerArtists.docs.length !== 0 && 
                        <div className="list-item-personal-description-addictional-container">    
                            <h3 className="list-item-personal-description-title">Former Artists</h3>
                            { group.formerArtists !== undefined && <ArtistList artists={group.formerArtists} showPaginate={false} /> }
                        </div>
                    }
                    
                    { group.videoSrc !== "" &&
                        <div className="list-item-personal-description-addictional-container">
                            <h3 className="list-item-personal-description-title">Latest Video</h3> 
                            <iframe 
                                className="video" 
                                src={group.videoSrc}
                                title="YouTube video player" 
                                frameborder="0" 
                                allow="accelerometer autoplay clipboard-write encrypted-media gyroscope" 
                                allowfullscreen="allowfullscreen" 
                            >
                            </iframe>  
                        </div>
                    }
                </div>
            }

            { (isLoading === false && isError === 404) &&
                <Error404/>
            }
        </div>
    )
}

export default Group

// project/vuejs3/src/pages/Group/Group.vue
<template>
    <div>
        <div v-if="isLoading === false && isError === null" class="flex-container-column">

            <img class="img" :src="group.groupImageLink" alt="bild"/>  

            <h1 class="title list-item-title">{{group.name}}</h1>

            <div className="list-item-personal-description">
                <div v-if="group.debutDate !== ''" className="list-item-personal-description-container">
                    <h3 className="list-item-personal-description-title">Debut Date</h3>
                    <p className="list-item-personal-description-text">{{group.debutDate}}</p>
                </div>

                <div v-if="group.companies !== ''" className="list-item-personal-description-container">
                    <h3 className="list-item-personal-description-title">Companies</h3>
                    <p className="list-item-personal-description-text">{{group.companies}}</p>
                </div>

                <div v-if="group.fandomName !== ''" className="list-item-personal-description-container">
                    <h3 className="list-item-personal-description-title">Fandom Name</h3>
                    <p className="list-item-personal-description-text">{{group.fandomName}}</p>
                </div>
            </div>

            <div v-if="group.facts !== '' && group.facts !== '<p><br></p>'" className="list-item-personal-description-addictional-container">
                <h3 className="list-item-personal-description-title">Facts</h3>
                <QuillEditor 
                    theme="bubble"
                    class="readQuill"
                    v-bind:content="group.facts" 
                    content-type="html"
                    v-bind:readOnly="true"
                />
            </div>

            <div v-if="group.artists.docs.length !== 0" className="list-item-personal-description-addictional-container">
                <h3 className="list-item-personal-description-title">Active Members</h3>
                <ArtistList v-if="group.artists !== undefined" :artists="group.artists" :showPaginate="false"/>
            </div>

            <div v-if="group.formerArtists.docs.length !== 0" className="list-item-personal-description-addictional-container">
                <h3 className="list-item-personal-description-title">Former Members</h3>
                <ArtistList v-if="group.formerArtists !== undefined" :artists="group.formerArtists" :showPaginate="false"/>
            </div>
                    
            <div v-if="group.videoSrc !== ''" className="list-item-personal-description-addictional-container">
                <h3 className="list-item-personal-description-title">Latest Video</h3> 
                <iframe 
                    class="video" 
                    :src="group.videoSrc"
                    title="YouTube video player" 
                    frameborder="0" 
                    allow="accelerometer autoplay clipboard-write encrypted-media gyroscope" 
                    allowfullscreen
                >
                </iframe>
            </div>
        </div>

        <div v-if="isLoading === false && isError === 404">
            <Error404/>
        </div>
        
    </div>
</template>

<script>
    import Axios from 'axios'
    import Error404 from '../Error/Error404.vue'
    import { QuillEditor } from '@vueup/vue-quill'
    import ArtistList from '../../components/Artist/ArtistList.vue'

    export default {
        name: 'Group',
        components: {
            Error404,
            QuillEditor,
            ArtistList
        },
        props: ['id'],
        data: () => {
            return {
                group: {},
                isLoading: true,
                isError: null,
                options: {
                    readOnly: true,
                }
            }
        },
        mounted() {            
            Axios
            .get(`http://localhost:8000/groups/${this.id}`)
            .then((res) => {
                this.group = res.data
                this.isLoading = false
            })
            .catch((err) => {
                this.isError = err.rsponse.status
                this.isLoading = false
            })
        }
    }
</script>
