// project/reactjs/src/js/pages/Group/GroupCreate.js
import React from 'react'
import GroupForm from '../../components/Group/GroupForm'

function GroupCreate() {
    const data = {}

    return (    
        <div>
            <h2 className="title">Create Group</h2>
            
            <GroupForm data={data} actionType={"create"}/>
        </div>
    )
}  
  
export default GroupCreate

// project/vuejs3/src/pages/Group/GroupCreate.vue
<template>
    <div>
        <h2 class="title">Create Group</h2>
        
        <GroupForm :data="data" :actionType="actionType"/>
    </div>
</template>

<script>
    import GroupForm from '../../components/Group/GroupForm.vue'

    export default {
        name: 'GroupCreate',
        components: {
            GroupForm
        },
        data: function() {
            return {
                data: {},
                actionType: 'create'
            }
        }
    }

</script>
