// project/sveltejs/src/pages/Group/Groups.svelte
<script>
    import { onMount } from 'svelte'
    import Axios from 'axios'
    import Error422 from "../Error/Error422.svelte"
    import GroupList from "../../components/Group/GroupList.svelte"

    import { limit as limit_value} from '../../store/store'
    
    let limit; 

    limit_value.subscribe(value => {
		limit = value;
	});

    let isLoading = true
    let isError = null
    let groups = {}
    
	onMount(async () => {
        getData()
    })

    function getData() {
        let page = 1

        if(Object.keys(groups).length !== 0) {
            page = groups.nextPage
        }

        Axios
        .get(`http://localhost:8000/groups?page=${page}&limit=${limit}`)
        .then((res) => {
            let groupsList = []

            if(groups.docs !== undefined) {
                groupsList = groups.docs
            }  

            let newObject = {
                ...res.data,
                docs: groupsList.concat(res.data.docs)
            }
            groups = newObject
            isLoading = false
        })
        .catch((err) => {
            isError = err.response.status
            isLoading = false
        })
    }
    
    function handleMoreButton() {
        getData()
    }
</script>

{#if isLoading === false && isError === null}
    <h1 class="title">Groups</h1>

    <GroupList groups={groups} showButtons={false} showPaginate={true} handleMoreButton={handleMoreButton}/>
{/if}

{#if isLoading === false && isError === 422}
    <Error422 />
{/if}

// project/vuejs3/src/pages/Group/Groups.vue
<template>
    <div>
        <div v-if="isLoading === false && isError === null">
            <h1 class="title">Groups</h1>

            <GroupList :groups="groups" :showButtons="false" :showPaginate="true" :handleMoreButton="handleMoreButton"/>
        </div>
                
        <Error422 v-if="isLoading === false && isError === 422"/>
    </div>
</template>

<script>
    import Axios from 'axios'
    import GroupList from '../../components/Group/GroupList.vue'
    import Error422 from '../Error/Error422.vue'
    import store from '../../store/store.js'

    export default {
        name: "Groups",
        components: {
            GroupList,
            Error422
        },
        computed: {
            limit() {
                return store.state.limit
            }
        },
        data: function() {
            return {
                isLoading: true,
                groups: {},
                isError: null
            }
        },
        mounted() {
            Axios
            .get(`http://localhost:8000/groups?page=1&limit=${this.limit}`)
            .then((res) => {
                this.groups = res.data
                this.isLoading = false
            })
            .catch((err) => {
                this.isError = err.response.status
                this.isLoading = false
            })
        },
        methods: {
            handleMoreButton: function() {
                Axios
                .get(`http://localhost:8000/groups?page=${this.groups.nextPage}&limit=${this.limit}`)
                .then((res) => {
                    let groupsList = this.groups.docs  
                    let newObject = {
                        ...res.data,
                        docs: groupsList.concat(res.data.docs)
                    }
                    this.groups = newObject
                })
                .catch((err) => {
                    this.isError = err.response.status
                    this.isLoading = false
                })
            }
        }
    }
</script>
