// project/vuejs3/src/components/Group/GroupList.vue
<template>
    <div class="flex-container-column">
        <div class="list-container">
            <div v-for="item in groups.docs" :key="item._id">
                <GroupItem :item="item" :showButtons="showButtons"/>
            </div>
        </div>

        <div class="flex-container-row">
            <div class="flex-container-column margin20">
                <button v-if="groups.hasNextPage" class="button" v-on:click="handleMoreButton">Load More</button>
            </div>
        </div>
    </div>
</template>

<script>
    import GroupItem from './GroupItem.vue'

    export default {
        name: "GroupList",
        components: {
            GroupItem
        }, 
        props: ['handleMoreButton', 'groups', 'showPaginate', 'showButtons']
    }
</script>

// project/sveltejs/src/components/Group/GroupList.svelte
<script>
    import GroupItem from './GroupItem.svelte'

    export let groups
    export let showButtons
    export let showPaginate
    export let handleMoreButton
    export let setUpdate
    export let update
</script>

<div class="flex-container-column">
    <div class="list-container">
        {#each groups.docs as item}
            <GroupItem item={item} showButtons={showButtons} />
        {/each}
    </div>

    <div>
        {#if showPaginate}
            <div class="flex-container-row">
                <div class="flex-container-column margin20">
                    {#if groups.hasNextPage } 
                        <button class="button" on:click={() => handleMoreButton()}>Load More</button>
                    {/if}
                </div>
            </div>
        {/if}
    </div>
</div>
