// project/reactjs/src/js/components/Group/GroupItem.js
import React, { useState } from 'react'
import Axios from 'axios'
import 'material-design-icons/iconfont/material-icons.css'  
import { Link, Redirect } from "react-router-dom"   

function GroupItem(props) {
    const [isRedirect, setIsRedirect] = useState(false)
    const [redirectLink, setRedirectLink] = useState('')

    const deleteGroup = (event, groupId) => {
        event.preventDefault()
        event.stopPropagation()
        
        if(window.confirm('Are you sure you want to delete?')) {
                
            Axios
            .delete(`http://localhost:8000/groups/${groupId}`)
            .then((res) => {
                if(res.status === 200) {
                    window.location.reload() 
                }
            })
            .catch((err) => {
                if(window.confirm('Something went wrong please try it later again?')) {
                }
            })
        }
    }

    const updateGroup = (event, groupId) => {
        event.preventDefault()
        event.stopPropagation()

        setRedirectLink(`/groups/${groupId}/update`)
        setIsRedirect(true)
    }

    return (
        <Link to={`/groups/${props.item._id}`} className="list-item-container">
            { props.showButtons && 
                <div className="list-item-button-container">
                    <div className="flex-container-column">
                        <button 
                            className="list-item-button"
                            onClick={event => updateGroup(event, props.item._id)}
                        >
                            <span className="material-icons list-item-icon">mode_edit</span>
                        </button>
                    </div>
                    <div className="flex-container-column">
                        <button 
                            className="list-item-button"
                            onClick={event => deleteGroup(event, props.item._id)}
                        >
                            <span className="material-icons list-item-icon">delete</span>
                        </button>
                    </div>
                </div>
            }

            <div className="list-item-img-container">
                <img src={props.item.groupImageLink} alt="bild" className="list-item-img"/>
            </div>

            <div className="list-item-descibtion">
                <p className="list-item-p">{props.item.name}</p>
            </div>

            { isRedirect === true &&      
                <Redirect to={redirectLink}/>
            }
        </Link>
    )
} 

export default GroupItem

// project/sveltejs/src/components/Group/GroupItem.svelte
<script>
    import Axios from 'axios'
    import 'material-design-icons/iconfont/material-icons.css'  
    import { Link, useNavigate } from 'svelte-navigator'

	const navigate = useNavigate()

    export let showButtons
    export let item

    function deleteGroup(event, groupId) {
        event.preventDefault()
        event.stopPropagation()

        if(window.confirm('Are you sure you want to delete?')) {
            Axios
            .delete(`http://localhost:8000/groups/${groupId}`)
            .then((res) => {
                if(res.status === 200) {
                    window.location.reload(false) 
                }
            })
            .catch((err) => {
                console.log(err)
                if(window.confirm('Something went wrong please try it later again?')) {
                }
            })
        }
    }

    function updateGroup(event, groupId) {
        event.preventDefault()
        event.stopPropagation()

        navigate(`/groups/${groupId}/update`)
    }

</script>

<Link to={`/groups/${item._id}`} class="list-item-container">
    {#if showButtons }
        <div class="list-item-button-container">
            <div class="flex-container-column">
                <button
                    class="list-item-button"
                    on:click={event => updateGroup(event, item._id)}
                >
                    <span class="material-icons list-item-icon">mode_edit</span>
                </button>
            </div>
            <div class="flex-container-column">
                <button 
                    class="list-item-button"
                    on:click={event => deleteGroup(event, item._id)}
                >
                    <span class="material-icons list-item-icon">delete</span>
                </button>
            </div>
        </div>
    {/if}

    <div class="list-item-img-container">
        <img src={item.groupImageLink} alt="bild" class="list-item-img"/>
    </div>

    <div class="list-item-descibtion">
        <p class="list-item-p">{item.name}</p>
    </div>
</Link>
