// example/vue-example/src/App.vue
<template>
    <div>
        <div class="title">
            <h2 v-if="name !== ''">Hey, {{name}}.</h2>
            <Hello v-else :name="defaultName" />
        </div>

        <div>
            <p>Count: {{count}}</p>

            <button v-on:click="increment">+</button>
            
            <button v-on:click="reset">Reset</button>
        </div>
    </div>
</template>
 
<script>
    import Hello from './components/Hello.vue'
    import store from './vuex/store.js'
 
    export default {
        name: 'App',
        props: ['name'],
        data: () => { 
            return {
                defaultName: 'Jenni',
            }
        },
        components: {
            Hello
        },
        computed: {
            count() {
                return store.state.count
            }
        },
        mounted() { console.log('mount') },
        methods: {
            exampleMethode: function() { console.log('methode') },
            increment: function() {
                store.commit('increment');
            },
            reset: function() {
                store.commit('reset');
            }
        }
    }
</script>
      
<style>
    @import './greeting.css'
</style>

// example/svelte-example/src/App.svelte
<script>
    import Hello from './components/Hello.svelte'
    import { onMount } from 'svelte'

	import { count } from './stores/store.js'

    let count_value;

	count.subscribe(value => {
		count_value = value;
	});
 
    function increment() {
      count.update(n => n + 1);
    }
 
    function reset() {
      count.set(0);
    }
 
    export let name
 
    let defaultName = 'Jenni'
 
    onMount(async () => { console.log('mount') })
 
    function exampleMethode() { console.log('methode') }
</script>
 
<div class="title">
    {#if name !== ''}
        <h2>Hey, {name}.</h2>
    {:else}
        <Hello name={defaultName} />
    {/if}
</div>

<p>Count: {count_value}</p>

<button on:click={increment}>+</button>
 
<button on:click={reset}>Reset</button>

<style>
    h2 {
        color: blue;
    }

    .title {
        background-color: black;
    }
</style>
