// project/vuejs3/src/pages/Account/Account.vue
<template>
    <div>
        <div v-if="isLoading === false && isError === null && data !== null">
            <h2 class="title">Account</h2>
            <form class="flex-container-column">
                <div class="form-width">
                    <div class="form-group">  
                        <input class="form-control" type="text" name="name" id="name" placeholder="E-Mail" :defaultValue="data.email" disabled/>
                        <label class="form-label" for="name">E-Mail</label>
                    </div>                    
                </div>
            </form>

            <div class="flex-container-row">
                <button class="button margin20" v-on:click="handleChangeEmail">Change E-Mail</button>
                <button class="button margin20" v-on:click="handleChangePassword">Change Password</button>
                <button class="button margin20" v-on:click="deleteAccount">Delete Account</button>
            </div>

            <ChangeEmail v-if="changeEmail"/>

            <ChangePassword v-if="changePassword"/>

        </div>

        <Error422 v-if="isLoading === false && isError === 422"/>

    </div>
</template>

<script>
    import Axios from 'axios'
    import ChangePassword from '../../components/Account/ChangePassword.vue'
    import ChangeEmail from '../../components/Account/ChangeEmail.vue'
    import Error422 from '../Error/Error422'

    export default {
        name: 'Account',
        components: {
            ChangePassword,
            ChangeEmail,
            Error422
        },
        data: function() {
            return {
                data: null,
                changeEmail: false,
                changePassword: false, 
                isLoading: true,
                isError: null
            }
        },
        mounted() {
            let headers = {headers: {'Authorization': 'Bearer ' + localStorage.getItem('jwtToken')}} 

            Axios
            .get('http://localhost:8000/dashboard/user', headers)
            .then((res) => {
                this.data = res.data
                this.isLoading = false
            })
            .catch((err) => {
                this.isError = err.response.status
                this.isLoading = false
            })
        },
        methods: {
            deleteAccount: function() {
                if(window.confirm('Are you sure you want to delete?')) {
                    let headers = {headers: {'Authorization': 'Bearer ' + localStorage.getItem('jwtToken')}} 

                    Axios
                    .delete('http://localhost:8000/dashboard/delete', headers)
                    .then(() => {
                        localStorage.removeItem('jwtToken')
                        window.location = 'http://localhost:3000/admin/signup'
                    })
                    .catch((err) => {
                        this.isError = err.response.status
                        this.isLoading = false
                    })
                }
            },
            handleChangeEmail: function() {
                if(this.changeEmail) {
                    this.changeEmail = false
                    this.changePassword = false
                }
                else {
                    this.changeEmail = true
                    this.changePassword = false
                }
            },
            handleChangePassword: function() {
                if(this.changePassword) {
                    this.changeEmail = false
                    this.changePassword = false
                }
                else {
                    this.changeEmail = false
                    this.changePassword = true
                }
            }
        }
    }
</script>

// project/reactjs/src/js/pages/Account/Account.js
import React, { useState, useEffect } from 'react'
import Axios from 'axios'
import ChangePassword from '../../components/Account/ChangePassword'
import ChangeEmail from '../../components/Account/ChangeEmail'
import Error422 from '../Error/Error422'

function Account() {
    const [data, setData] = useState(null)
    const [changeEmail, setChangeEmail] = useState(false)
    const [changePassword, setChangePassword] = useState(false)
    const [isLoading, setIsLoading] = useState(true)
    const [isError, setIsError] = useState(null)

    useEffect(() => {
        let headers = {headers: {'Authorization': 'Bearer ' + localStorage.getItem('jwtToken')}} 

        Axios
        .get('http://localhost:8000/dashboard/user', headers)
        .then((res) => {
            setData(res.data)
            setIsLoading(false)
        })
        .catch((err) => {
            setIsError(err.response.status)
            setIsLoading(false)
        })
    }, [])

    const deleteAccount = () => {
        if(window.confirm('Are you sure you want to delete?')) {
            let headers = {headers: {'Authorization': 'Bearer ' + localStorage.getItem('jwtToken')}} 

            Axios
            .delete('http://localhost:8000/dashboard/delete', headers)
            .then((res) => {
                localStorage.removeItem('jwtToken')
                window.location = 'http://localhost:3000/admin/signup'
            })
            .catch((err) => {
                setIsError(err.response.status)
                setIsLoading(false)
            })
        }
    }

    const handleChangeEmail = () => {
        if(changeEmail) {
            setChangeEmail(false)
            setChangePassword(false)
        }
        else {
            setChangeEmail(true)
            setChangePassword(false)
        }
    }

    const handleChangePassword = () => {
        if(changePassword) {
            setChangeEmail(false)
            setChangePassword(false)
        }
        else {
            setChangeEmail(false)
            setChangePassword(true)
        }
    }

    return (
        <div>
            { (isLoading === false && isError === null && data !== null) && 
                <div>
                    <h2 className="title">Account</h2>

                    { data !== null &&
                        <form className="flex-container-column">
                            <div className="form-width">
                                <div className="form-group">  
                                    <input className="form-control" type="text" name="name" id="name" placeholder="E-Mail" defaultValue={data.email} disabled/>
                                    <label className="form-label" htmlFor="name">E-Mail</label>
                                </div>                    
                            </div>
                        </form>
                    }

                    <div className="flex-container-row">
                        <button className="button margin20" onClick={() => handleChangeEmail()}>Change E-Mail</button>
                        <button className="button margin20" onClick={() => handleChangePassword()}>Change Password</button>
                        <button className="button margin20" onClick={() => deleteAccount()}>Delete Account</button>
                    </div>

                    { changeEmail && 
                        <ChangeEmail/>
                    }

                    { changePassword  && 
                        <ChangePassword/>
                    }

                </div>
            }

            { (isLoading === false && isError === 422) && 
                <Error422/>
            }
        </div>
    )
}

export default Account
