// project/reactjs/src/js/routes/Routes.js
import React from 'react'  
import {Switch} from 'react-router-dom'  

import PublicRoute from './PublicRoute'
import PrivateRoute from './PrivateRoute'

import SignUp from '../pages/Auth/SignUp'
import Login from '../pages/Auth/Login'

import Artists from '../pages/Artist/Artists'
import Groups from '../pages/Group/Groups'
import Search from '../pages/Other/Search'

import Artist from '../pages/Artist/Artist'
import ArtistCreate from '../pages/Artist/ArtistCreate'
import ArtistUpdate from '../pages/Artist/ArtistUpdate'

import Group from '../pages/Group/Group'
import GroupCreate from '../pages/Group/GroupCreate'
import GroupUpdate from '../pages/Group/GroupUpdate'

import Dashboard from '../pages/Account/Dashboard'
import Account from '../pages/Account/Account'

import Home from '../pages/Other/Home'

import Error404 from '../pages/Error/Eroro404'

import { useLocation } from "react-router-dom";
import { useEffect } from 'react'

function Routes() {
    const { pathname } = useLocation();

    useEffect(() => {
        window.scrollTo(0, 0);
    }, [pathname]);


    return (
        <Switch>
            <PublicRoute exact strict path="/" component={Home} restricted={false}/>
            <PublicRoute exact strict path="/admin/signup" component={SignUp} restricted={true}/>
            <PublicRoute exact strict path="/admin/login" component={Login} restricted={true}/>
            
            <PublicRoute exact strict path="/artists" component={Artists} restricted={false}/>
            <PublicRoute exact strict path="/groups" component={Groups} restricted={false}/>
            <PublicRoute exact strict path="/search" component={Search} restricted={false}/>

            <PrivateRoute exact strict path="/artists/create" component={ArtistCreate}/>
            <PublicRoute exact strict path="/artists/:id" component={Artist}/>
            <PrivateRoute exact strict path="/artists/:id/update" component={ArtistUpdate}/>

            <PrivateRoute exact strict path="/groups/create" component={GroupCreate}/>
            <PublicRoute exact strict path="/groups/:id" component={Group}/>
            <PrivateRoute exact strict path="/groups/:id/update" component={GroupUpdate}/>

            <PrivateRoute exact strict path="/dashboard" component={Dashboard}/>
            <PrivateRoute exact strict path="/dashboard/account" component={Account}/>

            <PublicRoute component={Error404}/>
        </Switch>
    )
}

export default Routes

// project/sveltejs/src/routes/Routes.svelte
<script>
    import Groups from "../pages/Group/Groups.svelte"
    import Group from "../pages/Group/Group.svelte"
    import Artists from "../pages/Artist/Artists.svelte"
    import Artist from "../pages/Artist/Artist.svelte"
    import SignUp from "../pages/Auth/SignUp.svelte"
    import Login from "../pages/Auth/Login.svelte"
    import Search from  "../pages/Other/Search.svelte"
    import ArtistCreate from "../pages/Artist/ArtistCreate.svelte"
    import GroupCreate from "../pages/Group/GroupCreate.svelte"
    import ArtistUpdate from "../pages/Artist/ArtistUpdate.svelte"
    import GroupUpdate from "../pages/Group/GroupUpdate.svelte"
    import Dashboard from '../pages/Account/Dashboard.svelte'
    import Account from '../pages/Account/Account.svelte'
    import Home from '../pages/Other/Home.svelte'

    import PrivateRoute from "./PrivateRoute.svelte"
    import PublicRoute from "./PublicRoute.svelte"
</script>

<PrivateRoute path="dashboard" let:location>
    <Dashboard />
</PrivateRoute>

<PrivateRoute path="dashboard/account" let:location>
    <Account />
</PrivateRoute>

<PrivateRoute path="groups/create" let:location>
    <GroupCreate />
</PrivateRoute>

<PrivateRoute path="artists/create" let:location>
    <ArtistCreate />
</PrivateRoute>

<PrivateRoute path="groups/:id/update" let:location let:params>
    <GroupUpdate id={params.id}/>
</PrivateRoute>

<PrivateRoute path="artists/:id/update" let:location let:params>
    <ArtistUpdate id={params.id}/>
</PrivateRoute>

<PublicRoute path="search" restricted={false} let:params let:location>
    <Search params={params} />
</PublicRoute>

<PublicRoute path="admin/login" restricted={true} let:params let:location>
    <Login />
</PublicRoute>

<PublicRoute path="admin/signup" restricted={true}>
    <SignUp />
</PublicRoute>

<PublicRoute path="groups" restricted={false}>
    <Groups />
</PublicRoute>

<PublicRoute path="groups/:id" let:params restricted={false}>
    <Group id={params.id}/>
</PublicRoute>

<PublicRoute path="artists" restricted={false}>
    <Artists />
</PublicRoute>

<PublicRoute exact path="artists/:id" let:params restricted={false}>
    <Artist id={params.id}/>
</PublicRoute>

<PublicRoute path="" restricted={false} let:params let:location>
    <Home />
</PublicRoute>
