// project/vuejs3/src/pages/Artist/Artists.vue
<template>
    <div>
        <div v-if="isLoading === false && isError === null">
            <h1 class="title">Artists</h1>
                    
            <ArtistList :artists="artists" :showPaginate="true" :handleMoreButton="handleMoreButton"/>
        </div>

        <Error422 v-if="isLoading === false && isError === 422"/>

    </div>
</template>

<script>
    import Axios from 'axios'
    import ArtistList from '../../components/Artist/ArtistList.vue'
    import Error422 from '../Error/Error422.vue'
    import store from '../../store/store.js'

    export default {
        name: "Artists",
        components: {
            ArtistList,
            Error422
        },
        computed: {
            limit() {
                return store.state.limit
            }
        },
        data: () => {
            return {
                isLoading: true,
                artists: {},
                isError: null
            }
        },
        mounted() {
            Axios
            .get(`http://localhost:8000/artists?page=1&limit=${this.limit}`)
            .then((res) => {
                this.artists = res.data
                this.isLoading = false
            })
            .catch((err) => {
                this.isError = err.response.staatus
                this.isLoading = false
            })
        },
        methods: {
            handleMoreButton: function() {
                Axios
                .get(`http://localhost:8000/artists?page=${this.artists.nextPage}&limit=${this.limit}`)
                .then((res) => {
                    let artistsList = this.artists.docs 
                    let newObject = {
                        ...res.data,
                        docs: artistsList.concat(res.data.docs)
                    }
                    this.artists = newObject
                    this.isLoading = false
                })
                .catch((err) => {
                    this.isError = err.response.status
                    this.isLoading = false
                })
            }
        }
    }
</script>

// project/reactjs/src/js/pages/Artist/Artists.js
import React, { useState, useEffect } from 'react'
import Axios from 'axios'
import ArtistList from '../../components/Artist/ArtistList'
import Error422 from '../Error/Error422'
import { connect } from 'react-redux' 

function Artists(props) {
    const [isLoading, setIsLoading] = useState(true)
    const [artists, setArtists] = useState({})
    const [isError, setIsError] = useState(null)

    useEffect(() => {
        Axios
        .get(`http://localhost:8000/artists?page=1&limit=${props.limit}`)
        .then((res) => {
            setArtists(res.data)
            setIsLoading(false)
        })
        .catch((err) => {
            setIsError(err.response.status)
            setIsLoading(false)
        })

        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [])

    const handleMoreButton = () => {
        Axios
        .get(`http://localhost:8000/artists?page=${artists.nextPage}&limit=${props.limit}`)
        .then((res) => {
            let artistsList = artists.docs 
            let newObject = {
                ...res.data,
                docs: artistsList.concat(res.data.docs)
            }
            setArtists(newObject)
            setIsLoading(false)
        })
        .catch((err) => {
            setIsError(err.response.status)
            setIsLoading(false)
        })
    }

    return(
        <div>
            { (isLoading === false && isError === null) &&
                <div>
                    <h1 className="title">Artists</h1>
                    
                    <ArtistList artists={artists} showPaginate={true} handleMoreButton={handleMoreButton}/>
                </div>
            }

            { (isLoading === false && isError === 422) &&
                <Error422/>
            }
        </div>
    )
}

const mapStateToProps = state => {
    return {
        limit: state.search.limit
    };
};

export default connect(mapStateToProps)(Artists)
