// project/reactjs/src/js/pages/Artist/ArtistUpdate.js
import React, { useState, useEffect } from 'react' 
import Axios from 'axios' 
import ArtistForm from '../../components/Artist/ArtistForm'
import { useParams } from 'react-router-dom'
import Error422 from '../Error/Error422'

function ArtistUpdate() {
    const [isLoading, setIsLoading] = useState(true)
    const {id} = useParams() 
    const [data, setData] = useState({})
    const [isError, setIsError] = useState(null)

    useEffect (() => {        
        Axios
        .get((`http://localhost:8000/artists/${id}`))
        .then((res) => {
            setData(res.data)
            setIsLoading(false)
        })
        .catch((err) => {
            setIsError(err.response.status)
            setIsLoading(false)
        })
        
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [])

    return(
        <div>
            { (isLoading === false && isError === null) &&
                <div>
                    <h2 className="title">Update Artist</h2>

                    <ArtistForm data={data} actionType="update" id={id}/>
                </div>
            }

            { (isLoading === false && isError === 422) &&
                <Error422/>
            }
        </div>
    )
} 
  
export default ArtistUpdate

// project/vuejs3/src/pages/Artist/ArtistUpdate.vue
<template>
    <div>
        <div v-if="isLoading === false && isError === null">
            <h2 class="title">Update Artist</h2>

            <ArtistForm :data="data" :actionType="actionType" :id="id"/>
        </div>

        <Error422 v-if="isLoading === false && isError === 422"/>
    </div>
</template>

<script>
    import Axios from 'axios' 
    import ArtistForm from '../../components/Artist/ArtistForm.vue'
    import Error422 from '../Error/Error422'

    export default {
        name: 'artistUpdate',
        components: {
            ArtistForm,
            Error422
        },
        props: ['id'],
        data: function() {
            return {
                isLoading: true,
                data: {},
                isError: null,
                actionType: 'update'
            }
        },
        mounted() {
            Axios
            .get((`http://localhost:8000/artists/${this.id}`))
            .then((res) => {
                this.data = res.data
                this.isLoading = false
            })
            .catch((err) => {
                this.isError = err.response.status
                this.isLoading = false
            })
        }
    }
</script>
