// project/reactjs/src/js/pages/Artist/ArtistCreate.js
import React from 'react'
import ArtistForm from '../../components/Artist/ArtistForm'

function ArtistCreate() {
    const data = {}

    return (
        <div>
            <h2 className="title">Create Artist</h2>
            
            <ArtistForm data={data} actionType={"create"}/>
        </div>
    )
} 
  
export default ArtistCreate

// project/vuejs3/src/pages/Artist/ArtistCreate.vue
<template>
    <div>
        <h2 class="title">Create Artist</h2>
            
        <ArtistForm :data="data" :actionType="actionType"/>
    </div>
</template>

<script>
    import ArtistForm from '../../components/Artist/ArtistForm.vue'

    export default {
        name: 'ArtistCreate',
        components: {
            ArtistForm
        },
        data: function() {
            return {
                data: {},
                actionType: 'create'
            }
        }
    }
</script>
