// project/vuejs3/src/components/Layout/Navigation.vue
<template>
    <nav>
        <ul>
            <li>
                <router-link :to="{name: 'search'}">
                    <i class="material-icons">
                        search
                    </i>
                </router-link>
            </li>
            <li>
                <router-link :to="{name: 'groups'}">
                    <span>Groups</span>
                </router-link>
            </li>
            <li>
                <router-link :to="{name: 'artists'}">
                        <span>Artists</span>
                </router-link>
            </li>
            <li v-if="token !== null">
                <router-link :to="{name:'dashboardAccount'}">
                    <i class="material-icons">
                        person
                    </i>
                </router-link>
                <ul>
                    <li>
                        <router-link class="nav-item" :to="{name: 'dashboard'}">
                            <span>Dashboard</span>
                        </router-link>
                    </li>
                    <li>
                        <router-link class="nav-item" :to="{name: 'dashboardAccount'}">
                            <span>My Account</span>
                        </router-link>
                    </li>
                    <li>
                        <router-link class="nav-item" :to="{name: 'artistsCreate'}">
                            <span>Create Artist</span>
                        </router-link>
                    </li>  
                    <li>
                        <router-link class="nav-item" :to="{name: 'groupsCreate'}">
                            <span>Create Group</span>
                        </router-link>
                    </li>
                    <li>
                        <button class="nav-item nav-button" v-on:click="logout">
                            <span>Logout</span>
                        </button>
                    </li>
                </ul>
            </li>
        </ul>
    </nav>
</template>

<script>
    export default {
        name: 'Navigation',
        data: function() {
            return {
                token: window.localStorage.getItem('jwtToken')
            }
        },
        methods: {
            logout: function() {
                localStorage.removeItem('jwtToken')
                window.location = 'http://localhost:8080/admin/login'
            }
        }
    }
</script>

// project/reactjs/src/js/components/Layout/Navigation.js
import React from 'react' 
import { Link } from 'react-router-dom' 

function Navigation() {
    
    const logout = () => {
        localStorage.removeItem('jwtToken') 
        window.location = 'http://localhost:3000/admin/login' 
    }

    return (
        <nav>
            <ul>
                <li>
                    <Link to="/search">
                        <i className="material-icons">
                            search
                        </i>
                    </Link>
                </li>
                <li>
                    <Link to="/groups">
                        <span>Groups</span>
                    </Link>
                </li>
                <li>
                    <Link to="/artists">
                        <span>Artists</span>
                    </Link>
                </li>
                { localStorage.getItem('jwtToken') !== null &&
                    <li>
                        <Link to="/dashboard/account">
                            <i className="material-icons">
                                person
                            </i>
                        </Link>
                        <ul>
                            <li>
                                <Link to="/dashboard">
                                    <span>Dashboard</span>
                                </Link>
                            </li>
                            <li>
                                <Link to="/dashboard/account">
                                    <span>My Account</span>
                                </Link>
                            </li>
                            <li>
                                <Link to="/artists/create">
                                    <span>Create Artist</span>
                                </Link>
                            </li>  
                            <li>
                                <Link to="/groups/create">
                                    <span>Create Group</span>
                                </Link>
                            </li>
                            <li>
                                <button onClick={() => { logout() }}>
                                    <span>Logout</span>
                                </button>
                            </li>
                        </ul>
                    </li>
                }
            </ul>
        </nav>
    ) 
}

export default Navigation
