// project/vuejs3/src/pages/Other/Home.vue
<template>
    <div class="flex-container-column height100">
        <p clasS="home-text">Find your Korean Idol.</p>

        <div class="button">
            <router-link :to="{name: 'search'}" class="button">
                Go
            </router-link>
        </div>
    </div>
</template>

<script>
    export default {
        name: 'Home'
    }
</script>

// project/reactjs/src/js/pages/Other/Home.js
import React from 'react' 
import { Link } from 'react-router-dom' 

function Home() {
    return(
        <div className="flex-container-column height100">
            <p className="home-text">Find your Korean Idol.</p>

            <Link to="/search" className="button">
                Go
            </Link>
        </div>
    )
}

export default Home
