// project/sveltejs/src/components/Artist/ArtistItem.svelte
<script>
    import 'material-design-icons/iconfont/material-icons.css' 
    import Axios from 'axios'
    import { Link, useNavigate } from 'svelte-navigator'

    const navigate = useNavigate()

    export let showButtons
    export let item

    function deleteArtist(event, artistId) {
        event.preventDefault()
        event.stopPropagation()

        if(window.confirm('Are you sure you want to delete?')) {
            Axios
            .delete(`http://localhost:8000/artists/${item._id}`)
            .then((res) => {
                if(res.status === 200) {
                    window.location.reload() 
                }
            })
            .catch((err) => {
                if(window.confirm('Something went wrong please try it later again?')) {
                }
            })
        }
    }

    function updateArtist(event, artistId) {
        event.preventDefault()
        event.stopPropagation()

        navigate(`/artists/${item._id}/update`)
    }
</script>


<Link to={`/artists/${item._id}`} class="list-item-container">
    {#if showButtons}
        <div class="list-item-button-container">
            <div class="flex-container-column width50">
                <button 
                    class="list-item-button"
                    on:click={event => updateArtist(event, item._id)}
                    >
                    <span class="material-icons list-item-icon">mode_edit</span>
                </button>
            </div>
            <div class="flex-container-column width50">
                <button 
                    class="list-item-button"
                    on:click={event => deleteArtist(event, item._id)}
                >
                    <span class="material-icons list-item-icon">delete</span>
                </button>
            </div>
        </div>
    {/if}

    <div class="list-item-img-container">
        <img src={item.profileImageLink} alt="bild" class="list-item-img"/>
    </div>

    <div class="list-item-descibtion">
        <p class="list-item-p">{item.stageName}</p>
    </div>
</Link>

// project/vuejs3/src/components/Artist/ArtistItem.vue
<template>
    <div class="list-item-container">
        <router-link :to="{name: 'artistsId', params: {id: item._id}, props: true}">
            <div v-if="showButtons" class="list-item-button-container">
                <div class="flex-container-column width50">
                    <button 
                        class="list-item-button"
                        v-on:click="updateArtist(item._id, $event)"
                    >
                        <span class="material-icons list-item-icon">mode_edit</span>
                    </button>
                </div>
                <div class="flex-container-column width50">
                    <button 
                        class="list-item-button"
                        v-on:click="deleteArtist(item._id, $event)"
                    >
                        <span class="material-icons list-item-icon">delete</span>
                    </button>
                </div>
            </div>
                
            <div className="list-item-img-container">
                <img :src="item.profileImageLink" alt="bild" class="list-item-img"/>
            </div>

            <div class="list-item-descibtion">
                <p class="list-item-p">{{item.stageName}}</p>
            </div>
        </router-link>
    </div>
</template>

<script>
    import Axios from 'axios';

    export default {
        name: 'ArtistItem',
        props: ['item', 'showButtons'],
        methods: {
            updateArtist: function(id, event) {
                event.preventDefault()
                event.stopPropagation()
                
                this.$router.push({ name: 'artistsIdUpdate', params: { id: id } })
            },
            deleteArtist: function(id, event) {
                event.preventDefault()
                event.stopPropagation()

                if(window.confirm('Are you sure you want to delete?')) {
                    Axios
                    .delete(`http://localhost:8000/artists/${id}`)
                    .then((res) => {
                        if(res.status === 200) {
                            window.location.reload()
                        }
                    })
                    .catch(function() {
                        if(window.confirm('Something went wrong please try it later again?')) {
                            /**/
                        }
                    })
                }
            }
        }
    }
</script>
